// M97.F01.I02/I03/I04 — emit 产物校验（generated/schema.{sql,ts,dbml} 三件套）。
//
// 产物由 `npm run emit:schema` / `npm run emit:dbml` 生成（gitignored）；
// 本测试只校验「如果产物存在，则形状正确」。CI/新 clone 上未跑 emit 时跳过——
// 产物是本地 infra 副产物，不进仓。emit 链本身的 DB 侧验证在 db.smoke.test.ts。
import { describe, it, expect } from "vitest";
import { fnTest } from "./fn";
import { existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const GEN = resolve(__dirname, "../generated");
const isCi = process.env.CI === "true" || !!process.env.GITHUB_ACTIONS;

describe("M97.F01 emit 产物三件套（存在时校验形状）", () => {
  it.skipIf(!existsSync(resolve(GEN, "schema.sql")))("schema.sql 存在（emit:schema 已跑）", () => {
    expect(existsSync(resolve(GEN, "schema.sql"))).toBe(true);
  });

  // CI 没跑 emit:schema/sql,dbml 缺失;整组 skip。local dev emit 后跑。
  it.skipIf(isCi || !existsSync(resolve(GEN, "schema.sql")))("schema.sql：≥24 张 CREATE TABLE + 主键/FK 约束（pg_dump 或 pg_catalog fallback 产出）", () => {
    const sql = readFileSync(resolve(GEN, "schema.sql"), "utf8");
    const tables = sql.match(/CREATE TABLE public\.\w+/g) ?? [];
    expect(tables.length).toBeGreaterThanOrEqual(24);
    // FK 回填（V011 backwire）至少存在
    expect(/FOREIGN KEY|REFERENCES/.test(sql)).toBe(true);
    // 头部标明产出方式（pg_dump 原生 或 pg_catalog fallback）
    expect(sql.startsWith("-- generated by scripts/emit-schema.mjs")).toBe(true);
  });

  // schema.ts 总是由 CI 的 drizzle-kit pull 生成,这条不 skip
  fnTest(["M97.F01.I03"], "schema.ts：drizzle-kit pull 产物（pgTable 定义 ≥24 张）", () => {
    const ts = readFileSync(resolve(GEN, "schema.ts"), "utf8");
    expect(/pgTable\(/.test(ts)).toBe(true);
    const n = (ts.match(/pgTable\(/g) ?? []).length;
    expect(n).toBeGreaterThanOrEqual(24);
  });

  it.skipIf(isCi || !existsSync(resolve(GEN, "schema.dbml")))("schema.dbml：v-sql→DBML 产物（Table 定义 ≥24 + V013 后表名 inspection_ 前缀）", () => {
    const dbml = readFileSync(resolve(GEN, "schema.dbml"), "utf8");
    const n = (dbml.match(/^Table public\./gm) ?? []).length;
    expect(n).toBeGreaterThanOrEqual(24);
    // V013 rename：param_interface 两表带 inspection_ 前缀
    expect(/inspection_param_interfaces/.test(dbml)).toBe(true);
  });
});
