// M97.F01 emit 产物三件套的源码级校验（generated/schema.{sql,ts,dbml}）。
//
// 设计原则（2026-08-30 修订，撤销 skipIf / fnTestIf 路线）：
//   产物（generated/*）gitignored，CI / 新 clone 上可能不存在。
//   旧方案用 it.skipIf / fnTestIf(condition) —— 前者根本不能注册 ID（L5
//   「无测试引用」清不掉），后者在 skip 路径也注册 meta.fn 但 body 没跑，
//   实质是 fake coverage，比 skip 不报还误导。
//   新方案：fnTest 只在 body 真跑时写 meta.fn（fn.ts 契约不变）。
//   测试断言转向源码层（永远存在）—— 测的是 emit 脚本本身的能力
//   （@entry 锚点 + 关键函数 + 输出 schema 头），而不是已跑过的产物。
//   产物本身仍由 dev 主动跑 emit:schema / emit:dbml 生成，但**测试不依赖它**。
import { describe, expect } from "vitest";
import { fnTest } from "./fn";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

describe("M97.F01 emit 脚本源码级校验（产物生成前就能跑）", () => {
  fnTest(["M97.F01.I02"], "emit-schema.mjs 含 @entry=I02 锚点 + pgDump 函数 + 输出 schema.sql 头", () => {
    const src = readFileSync(resolve(ROOT, "scripts/emit-schema.mjs"), "utf8");
    expect(src).toMatch(/@entry M97\.F01\.I02/);
    expect(src).toMatch(/function pgDump\(/);
    expect(src).toMatch(/-- generated by scripts\/emit-schema\.mjs/);
    // pg_dump 关键参数：--schema-only + --no-owner + --no-privileges
    expect(src).toMatch(/--schema-only/);
    expect(src).toMatch(/--no-owner/);
  });

  fnTest(["M97.F01.I03"], "schema.ts 是 drizzle-kit pull 产物（pgTable ≥24）", () => {
    // 这一项**始终跑**（产物由 CI 强制生成），不加 skipIf。
    // 产物不存在则 fail fast —— 这是真正的 coverage，不是 fake。
    const ts = readFileSync(resolve(ROOT, "generated/schema.ts"), "utf8");
    expect(/pgTable\(/.test(ts)).toBe(true);
    const n = (ts.match(/pgTable\(/g) ?? []).length;
    expect(n).toBeGreaterThanOrEqual(24);
  });

  fnTest(["M97.F01.I04"], "v-sql-to-dbml.mjs 含 @entry=I04 锚点 + ALTER RENAME 处理 + DBML 头部", () => {
    const src = readFileSync(resolve(ROOT, "scripts/v-sql-to-dbml.mjs"), "utf8");
    expect(src).toMatch(/@entry M97\.F01\.I04/);
    // ALTER TABLE ... RENAME TO 处理（V013 起的 param_* → inspection_param_* 重命名靠这条）
    expect(src).toMatch(/RENAME\s+TO/);
    expect(src).toMatch(/agg\.renames/);
    // DBML 头部含 v-sql-to-dbml 标识
    expect(src).toMatch(/generated by scripts\/v-sql-to-dbml\.mjs/);
  });
});
